version: "3"
services:
    app:
        restart: on-failure
        healthcheck:
            test: ["curl", "localhost:8080"]
            timeout: 10s
            interval: 30s
            retries: 5
        build: .
        depends_on:
            - postgres
        environment:
            DB_URL: postgres://app:password@postgres:5432/app_db
            NODE_ENV: development
        ports:
            - "8080:8080"
        command: npm run docker
        volumes:
            - ./backend:/app/
            - ./package.json:/app/package.json

    postgres:
        image: postgres
        restart: on-failure
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
            timeout: 45s
            interval: 10s
            retries: 5
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db

            # db name, db user name, db user password are all in db/setup/init.sql
        volumes:
            - ./backend/db/setup/init.sh:/docker-entrypoint-initdb.d/01-init.sh
            - ./backend/db/setup/init.sql:/init.sql
